name: tftp
description: |
  A powerful TFTP package.
  This library provides a comprehensive set of functions and structures to simplify the creation of robust TFTP servers and clients.
topics:
  - tftp
version: 1.2.3
homepage: https://github.com/FourLeafTec/tftp

environment:
  sdk: ">=3.3.3 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5