name: tftp
description: Libraries for creating TFTP servers and clients.
topics:
  - tftp
version: 1.2.2
homepage: https://github.com/FourLeafTec/tftp

environment:
  sdk: ">=3.3.3 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5